### ISSUE TITLE
Publish wheels to pypi

### ISSUE THREAD

**Issue by videlec** [sagemath/pplpy#9]
moved from [gitlab issue #26](https://gitlab.com/videlec/pplpy/-/issues/26)

In order to make it easier to use pplpy, it would be nice if pre-built wheels are published to pypi.

The best option is probably via [cibuildwheel](https://pypi.org/project/cibuildwheel/).

**Comment by mkoeppe** [comment]
Done in 0.8.10 with https://github.com/sagemath/pplpy/blob/master/.github/workflows/dist.yml
